Add integration tests
arduino/libraries-repository-engine pull request #36
Opened 2021-05-24 09:41 UTC by per1234

This adds end to end testing of the tool to verify that the finished outputs are as expected.

2021-05-24 13:05 UTC, rsora commented on test/test_all.py
> +        # False when run on a machine with ClamAV installed.
As we were discussing in our chats, being this application something that has to run on a well defined environment, could make sense to include in this repo a `Dockerfile` with a replica of the destination linux environment, included all the tools that this engine uses (like ClamAV)

2021-05-24 13:06 UTC, rsora commented on test/test_all.py
> +            cd_command += " /d"
Same consideration as above, with a container that replicates the production environment we could get rid of this "OS dependant" code

2021-05-24 13:07 UTC, rsora approved these changes
The code is very ok, we could merge it and then address my comments about having a test container in a separate PR :+1:

2021-05-25 07:21 UTC, silvanocerza commented on test/test_all.py
> +    golden_logs_parent_path -- sub-path for both the actual and golden master logs
```suggestion
    logs_subpath -- sub-path for both the actual and golden master logs
```

2021-05-25 07:25 UTC, silvanocerza requested changes
Everything looks great, just a small comment to edit to reach approval. :+1:

2021-05-25 07:33 UTC, silvanocerza approved these changes

2021-05-25 07:34 UTC, merged

2021-05-25 07:34 UTC, per1234 commented on test/test_all.py
> +    golden_logs_parent_path -- sub-path for both the actual and golden master logs
Thanks Silvano!